name: "Multi Event Pipeline/Workflow"

on:
    push:
        branches:
            - master
            - production

    pull_request:
        branches:
            - master
        types:
            - closed
            - opened


    workflow_dispatch: 
  

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest

        steps:
            - name: "Running when the push happens"
              run: echo "Running on push"

    pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest

        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"


    on_pull_request_opened:
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        runs-on: ubuntu-latest
        steps:
            - name: "Runs on pull request opened"
              run: echo "Pull request opened"